openapi: 3.1.0
paths: {}
info:
  title: Core Components
  version: 1.0.0

components:
  parameters:
    XRequestId:
      name: x-request-id
      in: header
      description: Unique request identifier used for idempotency
      schema:
        type: string
    ClientHashId:
      name: clientHashId
      in: path
      description: Unique identifier of the client.
      required: true
      schema:
        type: string
        format: UUID
    CustomerHashId:
      name: customerHashId
      in: path
      description: Unique identifier of the customer.
      required: true
      schema:
        type: string
        format: UUID
    WalletHashId:
      name: walletHashId
      in: path
      description: Unique identifier of the wallet.
      required: true
      schema:
        type: string
        format: UUID
  schemas:
    UETR:
      type: string
      format: UUID
      description: Unique end-to-end transaction reference number.
      example: abc1234-5d6e-0a8b-c8d7-3a7706a0c312
    SystemReferenceNumber:
      type: string
      description: Nium One's reference number.
      example: RT0123456789
    SourceCurrency:
      type: string
      description: This field contains the 3-letter [ISO-4217 authorization currency code](https://www.iso.org/iso-4217-currency-codes.html).
      example: SGD
    DestinationCurrency:
      type: string
      description: This field contains the 3-letter [ISO-4217 transaction currency code](https://www.iso.org/iso-4217-currency-codes.html).
      example: SGD
    PayoutMethod:
      type: string
      description: Transaction payout method
      example: LOCAL
      enum:
        - LOCAL
        - SWIFT
        - WALLET
        - CASH
        - CARD
        - PROXY
        - CHECK
    SwiftType:
      type: string
      description: Transaction swift type.
      example: OUR
      enum:
        - OUR
        - BEN
        - SHA
    SourceAmount:
      type: string
      description: Transaction authorization amount.
      example: 1000
    SourceCountry:
      description: This field accepts the 2-letter [ISO-2 country code](https://docs.nium.com/apis/docs/currency-and-country-codes) of the destination country.
      type: string
      example: US
    DestinationCountry:
      description: This field accepts the 2-letter [ISO-2 country code](https://docs.nium.com/apis/docs/currency-and-country-codes) of the destination country.
      type: string
      example: SG
