openapi: 3.0.3
info:
  contact:
    email: experience@nium.com
    name: NIUM Platform
    url: https://www.nium.com
  description: NIUM Platform
  license:
    name: Copyright (c) 2023 NIUM
  title: NIUM Platform
  version: 10.31.2023
servers:
- url: https://gatewaysandbox.nium.com/
tags:
- name: Customer Fees
  description: REST API's for Cards  Reference Data
paths:
  /api/v1/client/{clientHashId}/customer/{customerHashId}/wallet/{walletHashId}/fees:
    post:
      parameters:
      - description: Unique client identifier generated and shared before API handshake.
        in: path
        name: clientHashId
        required: true
        schema:
          type: string
          example: '{{clientHashId}}'
      - description: Unique customer identifier generated on customer creation.
        in: path
        name: customerHashId
        required: true
        schema:
          type: string
      - description: Unique wallet identifier generated simultaneously with customer
          creation.
        in: path
        name: walletHashId
        required: true
        schema:
          type: string
      - description: Enter a unique UUID value
        in: header
        name: x-request-id
        schema:
          type: string
          example: '{{$guid}}'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomFeeResponseDTO'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletApiError'
          description: BadRequest
        '401':
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                type: string
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletApiError'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletApiError'
          description: Internal Server Error
      tags:
      - Customer Fees
      deprecated: false
      description: "This API allows you to levy custom fee. \n >\u26A0\uFE0F WARNING\
        \ \n >Consult with the Nium legal & compliance team and receive approval prior\
        \ to charging any customer fees. Do not use this API to charge fees without\
        \ explicit approval from Nium. Reach out to your Customer Success, Sales and\
        \ Solution Engineering teams at Nium for further guidance. Any fees charged\
        \ must be disclosed in the required customer terms and conditions as determined\
        \ by Nium legal & compliance."
      operationId: ChargeFee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomFeeRequestDTO'
        description: customFeeRequestDTO
        required: true
      summary: Charge Fee
      x-info:
        apiType: external
      security:
      - default: []
components:
  schemas:
    WalletApiError:
      properties:
        errors:
          description: List of errors occurred.
          example:
          - field1 is not valid
          - field2 is not valid
          items:
            type: string
          type: array
        message:
          description: Error message descriptor.
          example: Error message descriptor.
          type: string
        status:
          description: 'HttpStatus of the request : BAD_REQUEST, INTERNAL_SERVER_ERROR.'
          enum:
          - 200 OK
          - 400 BAD_REQUEST
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 500 INTERNAL_SERVER_ERROR
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          example: BAD_REQUEST
          type: string
      title: ApiError
      type: object
    ClientCustomTagDTO:
      properties:
        key:
          description: 'This field accepts the Client''s custom key of the tag.

            The maximum key length limit is 128 characters.'
          type: string
        value:
          description: 'This field accepts the Client''s custom value of the tag.

            The maximum value length limit is 256 characters.'
          type: string
      title: Client custom tag
      type: object
    CustomFeeRequestDTO:
      properties:
        tags:
          description: 'This is an array which accepts Client''s custom tags & values.

            Maximum 15 key-value pairs can be sent in tags.'
          items:
            $ref: '#/components/schemas/ClientCustomTagDTO'
          type: array
        amount:
          description: This field accepts the amount to be debited from the Customer's
            wallet.
          example: 50
          format: double
          type: number
        comments:
          description: 'This field accepts any comments for the custom fee to be levied.

            The maximum character limit is 255.'
          example: Custom fee comments
          type: string
        currency:
          description: This field accepts the 3-letter ISO-4217 currency code for
            the currency of the fee to be charged (supported for any currencies enabled
            in the Customer's wallet)
          example: SGD
          type: string
        feeName:
          description: 'This field accepts the name of the fee.

            Number of characters supported: 3 to 50.

            Note: This field only accepts alphanumeric characters with -_.(hyphen,
            underscore, dot, and space)'
          example: monthlyCharge_May-2022
          type: string
      required:
      - amount
      - currency
      - feeName
      title: Custom fee request
      type: object
    CustomFeeResponseDTO:
      properties:
        message:
          description: This field contains further details regarding the status of
            the fee.
          type: string
        status:
          description: This field contains the status such as success if the fee is
            levied successfully.
          type: string
        systemReferenceNumber:
          description: This field contains the unique system reference number.
          type: string
      title: Custom fee response
      type: object
  securitySchemes:
    default:
      in: header
      name: x-api-key
      type: apiKey
security:
- default: []
